[package]
name = "get-img"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
regex = "1.10.2"
reqwest = "0.11.23"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.109"
serenity = { version = "0.12.0", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "utils"] }
simple_logger = "4.3.3"
tokio = { version = "1.35", features = ["macros", "rt-multi-thread"] }

[profile.release]
# lto = true
# strip = true