[package]
name = "get-img"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
log = "0.4.21"
regex = "1.10.4"
reqwest = "0.12.4"
serde_json = "1.0.117"
serde = { version = "1.0.202", features = ["derive"] }
serenity = { version = "0.12.1", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "utils"] }
simple_logger = "5.0.0"
tokio = { version = "1.37", features = ["macros", "rt-multi-thread"] }
toml = "0.8.13"

[profile.release]
# lto = true
# strip = true