[package]
name = "get-img"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
log = "0.4.21"
regex = "1.10.3"
reqwest = "0.11.25"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serenity = { version = "0.12.1", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "utils"] }
simple_logger = "4.3.3"
tokio = { version = "1.36", features = ["macros", "rt-multi-thread"] }
toml = "0.8.10"

[profile.release]
# lto = true
# strip = true