name: Build and Release

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

env:
    CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build project
      run: cargo build --release

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: get-img
        path: target/release/get-img
